export const ApiErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  DUPLICATE_CUSTOMER: 'DUPLICATE_CUSTOMER',
  INVALID_NOMBA_CREDENTIALS: 'INVALID_NOMBA_CREDENTIALS',
  RATE_LIMITED: 'RATE_LIMITED',
  NOMBA_API_ERROR: 'NOMBA_API_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ApiErrorCode = (typeof ApiErrorCode)[keyof typeof ApiErrorCode];
